### ISSUE TITLE
Quest Log - Reputation gains can overlap in Rewards section sometimes

### ISSUE THREAD

**Issue by boktai1000** [Road-block/Reputable#5]
See example screenshots-

Sometimes, reputation gains and text in the Rewards section can overlap. I'm not sure of the exact conditions for this to occur, but it definitely happens quite a bit. If I close and re-open the Quest Log, often times the quest I was already selected on won't be displayed properly and I'll have to click a different quest and then click that one again for it to fix itself.

![image](https://user-images.githubusercontent.com/9054563/192193444-52bad5a0-5c16-40f5-8b3f-9c9771e00ed0.png)

**Comment by Road-block** [comment]
Fixed with https://github.com/Road-block/Reputable/commit/90ac280322ab2ebe663e85651770f152ea04e9a4 I believe.
Text might take a split second to adjust but should mostly settle below the last element (be it reward/money/currency etc)
